#ifndef MEMORY_LAYOUT_H
#define MEMORY_LAYOUT_H

#define BOOTLOADER_BEGIN	0x08000000
#define BOOTLOADER_VERSION_POS	(BOOTLOADER_BEGIN + ISR_VECTOR_LENGTH)
#define BOOTLOADER_FEATURES	(BOOTLOADER_VERSION_POS + 20)
#define BOOTLOADER_MAX_SIZE	APPLICATION_OFFSET

#define APPLICATION_BEGIN	(BOOTLOADER_BEGIN + APPLICATION_OFFSET)
#define APPLICATION_CRCSUM	(APPLICATION_BEGIN + ISR_VECTOR_LENGTH)
#define APPLICATION_FEATURES	(APPLICATION_CRCSUM + 8)
#define APPLICATION_END		0x08008000
#define APPLICATION_MAX_SIZE	(APPLICATION_END - APPLICATION_BEGIN)

#define RESET_REASON_MSG_LENGTH	0x10

#define RAM_BEGIN		0x20000000
#define RAM_LENGTH		0x2000
#define RAM_END			(RAM_BEGIN + RAM_LENGTH)

/* On GD32 we don't relocate segments (besides data) */
#define RELOC_SEGMENT_AT(_seg)	>_seg

/* Data copy and BSS fill requires 4-byte alignment of sections */
#define ALIGNMENT		4

#endif /* MEMORY_LAYOUT_H */
